"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";

export type Translation = { locale: string; display_name?: string; description?: string | null; question_text?: string; help_text?: string | null; label?: string };
export type Option = { id: string; value: string; label: string; sort_order: number; is_failure: boolean; translations: Translation[] };
export type Question = { id: string; version_section_id: string; question_group_id: string | null; code: string; question_text: string; help_text: string | null; question_type: string; is_required: boolean; unit: string | null; min_value: number | null; max_value: number | null; placeholder: string | null; sort_order: number; is_active: boolean; translations: Translation[]; options: Option[] };
export type Group = { id: string; version_section_id: string; code: string; name: string; sort_order: number; is_active: boolean; translations: Translation[]; questions: Question[] };
export type Section = { id: string; section_id: string; display_name: string; description: string | null; sort_order: number; is_required: boolean; is_active: boolean; translations: Translation[]; groups: Group[]; questions: Question[] };
export type BuilderData = { version: { id: string; version_number: number; status: string; notes: string | null }; form: { id: string; code: string; name: string }; sections: Section[] };

type SaveResult = { saving: boolean; message: string; error: string };
const initialSave: SaveResult = { saving: false, message: "", error: "" };

function useSave(url: string) {
  const router = useRouter();
  const [state, setState] = useState(initialSave);
  async function save(body: Record<string, unknown>) {
    if (state.saving) return;
    setState({ saving: true, message: "", error: "" });
    try {
      const response = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.error || "Unable to save.");
      setState({ saving: false, message: "Saved", error: "" });
      router.refresh();
    } catch (error) {
      setState({ saving: false, message: "", error: error instanceof Error ? error.message : "Unable to save." });
    }
  }
  return { state, save, restore: () => setState(initialSave) };
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="grid gap-1 text-sm font-medium text-slate-700">{label}{children}</label>;
}
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="min-h-9 rounded border border-slate-300 bg-white px-2 text-sm font-normal text-slate-900 shadow-sm outline-none focus:border-slate-600 focus:ring-1 focus:ring-slate-600" />; }
function Textarea(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className="min-h-20 rounded border border-slate-300 bg-white px-2 py-1 text-sm font-normal text-slate-900 shadow-sm outline-none focus:border-slate-600 focus:ring-1 focus:ring-slate-600" />; }
function SaveBar({ state, onSave, onRestore }: { state: SaveResult; onSave: () => void; onRestore: () => void }) { return <div className="flex items-center gap-3"><Button type="button" onClick={onSave} disabled={state.saving}>{state.saving ? "Saving..." : "Save"}</Button>{state.message && <span className="text-sm text-emerald-700">{state.message}</span>}{state.error && <><span className="text-sm text-red-700">{state.error}</span><button type="button" className="text-sm underline" onClick={onRestore}>Restore</button></>}</div>; }
function TranslationEditor({ versionId, resourceType, resourceId, translations }: { versionId: string; resourceType: "section" | "group" | "question" | "option"; resourceId: string; translations: Translation[] }) {
  const [locale, setLocale] = useState<"en" | "id-ID">("en");
  const current = translations.find((item) => item.locale === locale);
  const [values, setValues] = useState<Translation>(current ?? { locale });
  const save = useSave(`/api/admin/form-versions/${versionId}/translations`);
  const set = (key: string, value: string) => setValues((old) => ({ ...old, [key]: value }));
  const payload = resourceType === "question" ? { questionText: values.question_text ?? "", helpText: values.help_text ?? null } : resourceType === "option" ? { label: values.label ?? "" } : { displayName: values.display_name ?? "", description: values.description ?? null };
  return <div className="mt-3 border-l-2 border-slate-200 pl-3"><div className="mb-2 flex gap-1">{([["en", "English (EN)"], ["id-ID", "Indonesian (ID)"]] as const).map(([value, label]) => <button type="button" key={value} className={`border-b-2 px-2 py-1 text-xs font-semibold ${locale === value ? "border-slate-800 text-slate-900" : "border-transparent text-slate-500"}`} onClick={() => { setLocale(value); setValues(translations.find((item) => item.locale === value) ?? { locale: value }); }}>{label}</button>)}</div>{resourceType === "option" ? <Field label="Label"><Input value={values.label ?? ""} onChange={(event) => set("label", event.target.value)} /></Field> : <div className="grid gap-3 md:grid-cols-2"><Field label={resourceType === "question" ? "Question text" : "Display name"}><Input value={resourceType === "question" ? values.question_text ?? "" : values.display_name ?? ""} onChange={(event) => set(resourceType === "question" ? "question_text" : "display_name", event.target.value)} /></Field><Field label={resourceType === "question" ? "Help text" : "Description"}><Textarea value={resourceType === "question" ? values.help_text ?? "" : values.description ?? ""} onChange={(event) => set(resourceType === "question" ? "help_text" : "description", event.target.value || "")} /></Field></div>}<div className="mt-2"><SaveBar state={save.state} onSave={() => save.save({ resourceType, resourceId, locale, ...payload })} onRestore={save.restore} /></div></div>;
}

function SectionEditor({ versionId, section }: { versionId: string; section: Section }) {
  const save = useSave(`/api/admin/form-versions/${versionId}/sections/${section.id}`);
  const [values, setValues] = useState(section);
  const update = (key: keyof Section, value: unknown) => setValues((old) => ({ ...old, [key]: value }));
  return <section className="border border-slate-300 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Section</p><h2 className="text-lg font-semibold text-slate-950">{section.section_id}</h2></div><span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{values.is_active ? "Active" : "Inactive"}</span></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="Display name"><Input value={values.display_name} onChange={(e) => update("display_name", e.target.value)} /></Field><Field label="Description"><Textarea value={values.description ?? ""} onChange={(e) => update("description", e.target.value || null)} /></Field><Field label="Sort order"><Input type="number" min={0} value={values.sort_order} onChange={(e) => update("sort_order", Number(e.target.value))} /></Field></div><div className="mt-3 flex gap-5 text-sm"><label><input type="checkbox" checked={values.is_required} onChange={(e) => update("is_required", e.target.checked)} /> Required</label><label><input type="checkbox" checked={values.is_active} onChange={(e) => update("is_active", e.target.checked)} /> Active</label></div><div className="mt-3"><SaveBar state={save.state} onSave={() => save.save({ displayName: values.display_name, description: values.description, sortOrder: values.sort_order, isRequired: values.is_required, isActive: values.is_active })} onRestore={save.restore} /></div><TranslationEditor versionId={versionId} resourceType="section" resourceId={section.id} translations={section.translations} /><div className="mt-5 grid gap-4 border-t border-slate-200 pt-4">{section.groups.map((group) => <GroupEditor key={group.id} versionId={versionId} group={group} />)}{section.questions.filter((question) => !question.question_group_id).map((question) => <QuestionEditor key={question.id} versionId={versionId} question={question} />)}</div></section>;
}

function GroupEditor({ versionId, group }: { versionId: string; group: Group }) { const save = useSave(`/api/admin/form-versions/${versionId}/groups/${group.id}`); const [values, setValues] = useState(group); return <div className="border border-slate-200 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Group · {group.code}</p><div className="mt-2 grid gap-3 md:grid-cols-3"><Field label="Name"><Input value={values.name} onChange={(e) => setValues({ ...values, name: e.target.value })} /></Field><Field label="Sort order"><Input type="number" min={0} value={values.sort_order} onChange={(e) => setValues({ ...values, sort_order: Number(e.target.value) })} /></Field><label className="self-end text-sm"><input type="checkbox" checked={values.is_active} onChange={(e) => setValues({ ...values, is_active: e.target.checked })} /> Active</label></div><div className="mt-3"><SaveBar state={save.state} onSave={() => save.save({ name: values.name, sortOrder: values.sort_order, isActive: values.is_active })} onRestore={save.restore} /></div><TranslationEditor versionId={versionId} resourceType="group" resourceId={group.id} translations={group.translations} /><div className="mt-4 grid gap-3 border-t border-slate-100 pt-3">{group.questions.map((question) => <QuestionEditor key={question.id} versionId={versionId} question={question} />)}</div></div>; }

function QuestionEditor({ versionId, question }: { versionId: string; question: Question }) { const save = useSave(`/api/admin/form-versions/${versionId}/questions/${question.id}`); const [values, setValues] = useState(question); const update = (key: keyof Question, value: unknown) => setValues((old) => ({ ...old, [key]: value })); return <div className="border border-slate-200 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Question · {question.code} · {question.question_type}</p><div className="mt-2 grid gap-3 md:grid-cols-2"><Field label="Question text"><Textarea value={values.question_text} onChange={(e) => update("question_text", e.target.value)} /></Field><Field label="Help text"><Textarea value={values.help_text ?? ""} onChange={(e) => update("help_text", e.target.value || null)} /></Field><Field label="Unit"><Input value={values.unit ?? ""} onChange={(e) => update("unit", e.target.value || null)} /></Field><Field label="Placeholder"><Input value={values.placeholder ?? ""} onChange={(e) => update("placeholder", e.target.value || null)} /></Field><Field label="Minimum"><Input type="number" value={values.min_value ?? ""} onChange={(e) => update("min_value", e.target.value === "" ? null : Number(e.target.value))} /></Field><Field label="Maximum"><Input type="number" value={values.max_value ?? ""} onChange={(e) => update("max_value", e.target.value === "" ? null : Number(e.target.value))} /></Field><Field label="Sort order"><Input type="number" min={0} value={values.sort_order} onChange={(e) => update("sort_order", Number(e.target.value))} /></Field></div><div className="mt-3 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={values.is_required} onChange={(e) => update("is_required", e.target.checked)} /> Required</label><label><input type="checkbox" checked={values.is_active} onChange={(e) => update("is_active", e.target.checked)} /> Active</label></div><div className="mt-3"><SaveBar state={save.state} onSave={() => save.save({ questionText: values.question_text, helpText: values.help_text, isRequired: values.is_required, unit: values.unit, minValue: values.min_value, maxValue: values.max_value, placeholder: values.placeholder, sortOrder: values.sort_order, isActive: values.is_active })} onRestore={save.restore} /></div><TranslationEditor versionId={versionId} resourceType="question" resourceId={question.id} translations={question.translations} /><div className="mt-4 grid gap-2 border-t border-slate-100 pt-3">{question.options.length ? question.options.map((option) => <OptionEditor key={option.id} versionId={versionId} option={option} />) : <p className="text-sm text-slate-500">No options</p>}</div></div>; }

function OptionEditor({ versionId, option }: { versionId: string; option: Option }) { const save = useSave(`/api/admin/form-versions/${versionId}/options/${option.id}`); const [values, setValues] = useState(option); return <div className="border border-slate-200 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Option · value: {option.value}</p><div className="mt-2 grid gap-3 md:grid-cols-3"><Field label="Label"><Input value={values.label} onChange={(e) => setValues({ ...values, label: e.target.value })} /></Field><Field label="Sort order"><Input type="number" min={0} value={values.sort_order} onChange={(e) => setValues({ ...values, sort_order: Number(e.target.value) })} /></Field><label className="self-end text-sm"><input type="checkbox" checked={values.is_failure} onChange={(e) => setValues({ ...values, is_failure: e.target.checked })} /> Failure</label></div><div className="mt-3"><SaveBar state={save.state} onSave={() => save.save({ label: values.label, sortOrder: values.sort_order, isFailure: values.is_failure })} onRestore={save.restore} /></div><TranslationEditor versionId={versionId} resourceType="option" resourceId={option.id} translations={option.translations} /></div>; }

export function FormVersionBuilder({ data }: { data: BuilderData }) { const save = useSave(`/api/admin/form-versions/${data.version.id}`); const [notes, setNotes] = useState(data.version.notes ?? ""); return <main className="mx-auto max-w-6xl space-y-6 p-6 text-slate-900"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-5"><div><p className="text-sm text-slate-500">{data.form.code} · Version {data.version.version_number}</p><h1 className="text-2xl font-semibold text-slate-950">{data.form.name}</h1></div><div className="flex items-center gap-3"><span className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-900">DRAFT</span><a className="text-sm font-medium text-slate-700 underline" href="/protected/admin/forms">Back to Forms</a></div></header><section className="border border-slate-300 bg-white p-4"><h2 className="font-semibold text-slate-950">Version settings</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto]"><Field label="Notes"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><div className="self-end"><SaveBar state={save.state} onSave={() => save.save({ notes: notes || null })} onRestore={save.restore} /></div></div></section><section className="space-y-4"><div><h2 className="text-xl font-semibold text-slate-950">Sections</h2><p className="text-sm text-slate-500">Canonical fields and localized draft content</p></div>{data.sections.map((section) => <SectionEditor key={section.id} versionId={data.version.id} section={section} />)}</section></main>; }
